file_format: "1"
id: chocofi
name: Chocofi
type: shield
url: https://github.com/pashutk/chocofi
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - studio
siblings:
  - chocofi_left
  - chocofi_right
  - chocofi_dongle
