on: [push, pull_request, workflow_dispatch]

name: Build Fifi

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.5
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (Fifi Left)
        run: west build -s zmk/app -b nrfmicro_13 -- -DSHIELD=fifi_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Fifi DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/nrfmicro_13.dts.pre.tmp
      - name: Fifi Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 fifi_left_nrfmicro_13.uf2
      - name: Archive (Fifi Left)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: fifi_left_nrfmicro_13.uf2
      - name: West Build (Fifi Right)
        run: west build --pristine -s zmk/app -b nrfmicro_13 -- -DSHIELD=fifi_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Fifi Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 fifi_right_nrfmicro_13.uf2
      - name: Archive (Fifi Right)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: fifi_right_nrfmicro_13.uf2
